using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using System;
using System.Collections.Generic;
using System.Linq;

namespace _1010 {
    public class Save : GameObject {
        public Save() {
            Block = new PlayBlock(new List<int[]>() {
				new int[] { 1, 1 },
				new int[] { 1, 2 },
				new int[] { 2, 1 },
				new int[] { 0, 3 },
				new int[] { 1, 3 },
				new int[] { 1, 4 },
				new int[] { 2, 4 },
				new int[] { 1, 5 },
				new int[] { 2, 5 },
				new int[] { 3, 1 },
				new int[] { 3, 0 },
				new int[] { 4, 0 },
				new int[] { 4, 1 },
				new int[] { 5, 1 },
				new int[] { 6, 1 },
				new int[] { 0, 4 },
				new int[] { 1, 6 },
				new int[] { 1, 7 },
				new int[] { 2, 7 },
				new int[] { 2, 6 },
				new int[] { 7, 1 },
				new int[] { 8, 3 },
				new int[] { 8, 5 },
				new int[] { 8, 4 },
				new int[] { 5, 8 },
				new int[] { 4, 8 },
				new int[] { 3, 8 },
				new int[] { 3, 7 },
				new int[] { 3, 6 },
				new int[] { 2, 3 },
				new int[] { 2, 2 },
				new int[] { 3, 2 },
				new int[] { 4, 2 },
				new int[] { 5, 2 },
				new int[] { 6, 2 },
				new int[] { 6, 3 },
				new int[] { 7, 2 },
				new int[] { 7, 3 },
				new int[] { 7, 4 },
				new int[] { 7, 5 },
				new int[] { 7, 6 },
				new int[] { 7, 7 },
				new int[] { 6, 7 },
				new int[] { 6, 6 },
				new int[] { 4, 7 },
				new int[] { 5, 7 },
				new int[] { 5, 0 },
				new int[] { 0, 6 },
				new int[] { 3, 3 },
				new int[] { 6, 0 },
				new int[] { 1, 8 },
				new int[] { 2, 8 },
				new int[] { 3, 9 },
				new int[] { 4, 9 },
				new int[] { 5, 9 },
				new int[] { 6, 9 },
				new int[] { 7, 8 },
				new int[] { 8, 8 },
				new int[] { 8, 1 },
				new int[] { 8, 2 },
				new int[] { 9, 3 },
				new int[] { 8, 7 },
				new int[] { 8, 6 },
				new int[] { 9, 6 },
				new int[] { 9, 5 },
				new int[] { 9, 4 },
				new int[] { 6, 8 },
				new int[] { 0, 5 },
				new int[] { 7, 9 },
				new int[] { 9, 8 },
				new int[] { 9, 9 },
				new int[] { 8, 9 },
				new int[] { 9, 7 },
				new int[] { 7, 10 },
				new int[] { 8, 10 },
				new int[] { 9, 10 },
				new int[] { 10, 10 },
				new int[] { 10, 9 },
				new int[] { 10, 8 },
				new int[] { 14, 2 },
				new int[] { 14, 1 },
				new int[] { 13, 3 },
				new int[] { 13, 4 },
				new int[] { 13, 5 },
				new int[] { 13, 6 },
				new int[] { 15, 1 },
				new int[] { 16, 1 },
				new int[] { 16, 0 },
				new int[] { 17, 0 },
				new int[] { 18, 0 },
				new int[] { 19, 0 },
				new int[] { 19, 1 },
				new int[] { 20, 1 },
				new int[] { 21, 1 },
				new int[] { 21, 2 },
				new int[] { 21, 3 },
				new int[] { 21, 4 },
				new int[] { 22, 4 },
				new int[] { 22, 5 },
				new int[] { 22, 3 },
				new int[] { 22, 6 },
				new int[] { 21, 7 },
				new int[] { 21, 8 },
				new int[] { 19, 9 },
				new int[] { 20, 7 },
				new int[] { 20, 8 },
				new int[] { 19, 8 },
				new int[] { 19, 7 },
				new int[] { 18, 9 },
				new int[] { 17, 9 },
				new int[] { 16, 9 },
				new int[] { 14, 7 },
				new int[] { 14, 8 },
				new int[] { 15, 8 },
				new int[] { 16, 8 },
				new int[] { 15, 7 },
				new int[] { 17, 8 },
				new int[] { 17, 7 },
				new int[] { 18, 7 },
				new int[] { 18, 8 },
				new int[] { 16, 7 },
				new int[] { 16, 6 },
				new int[] { 15, 6 },
				new int[] { 14, 6 },
				new int[] { 14, 5 },
				new int[] { 14, 4 },
				new int[] { 14, 3 },
				new int[] { 16, 2 },
				new int[] { 16, 3 },
				new int[] { 15, 2 },
				new int[] { 15, 3 },
				new int[] { 15, 4 },
				new int[] { 15, 5 },
				new int[] { 17, 1 },
				new int[] { 17, 2 },
				new int[] { 18, 1 },
				new int[] { 20, 2 },
				new int[] { 20, 3 },
				new int[] { 19, 3 },
				new int[] { 19, 2 },
				new int[] { 18, 2 },
				new int[] { 20, 4 },
				new int[] { 20, 5 },
				new int[] { 21, 5 },
				new int[] { 21, 6 },
				new int[] { 20, 6 },
				new int[] { 19, 6 },
				new int[] { 13, 8 },
				new int[] { 13, 7 },
				new int[] { 12, 8 },
				new int[] { 15, 10 },
				new int[] { 15, 9 },
				new int[] { 14, 10 },
				new int[] { 14, 9 },
				new int[] { 13, 10 },
				new int[] { 13, 9 },
				new int[] { 12, 10 },
				new int[] { 12, 9 },
				new int[] { 11, 10 },
				new int[] { 11, 9 },
				new int[] { 11, 8 },
				new int[] { 8, 11 },
				new int[] { 9, 11 },
				new int[] { 10, 11 },
				new int[] { 11, 11 },
				new int[] { 12, 11 },
				new int[] { 13, 11 },
				new int[] { 14, 11 },
				new int[] { 10, 7 },
				new int[] { 12, 7 },
				new int[] { 11, 7 },
			}, new List<int[]>() {
				new int[] { 7, 7 },
				new int[] { 7, 2 },
				new int[] { 2, 2 },
				new int[] { 2, 7 },
				new int[] { 20, 2 },
				new int[] { 15, 2 },
				new int[] { 15, 7 },
				new int[] { 20, 7 },
				new int[] { 8, 8 },
				new int[] { 14, 8 },
			});
        }
        public Save(PlayBlock block) {
            Block = block;
        }

        public void Update(GameTime gt) {
            Block.Update(gt);
        }

        public void Draw(SpriteBatch sb) {
            Block.Draw(sb);
        }

        public PlayBlock Block { get; set; }
    }
}
